//
//  MainInteractor.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func requestData(request: Main.MainData.Request)
} 

class MainInteractor: MainBusinessLogic {
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    
    // MARK: Fetching data and sending response to MainPresenter)
    
    func requestData(request: Main.MainData.Request) {
        //Sending fetch request to worker
        worker = MainWorker()
        worker?.fetchData(onPage: request.page,completion: {[weak self] item in
            if let item = item {
                let response = Main.MainData.Response(mainData: item)
                self?.presenter?.presentSomething(response: response)
            }
        })
        
    }
}
