//
//  MainPresenter.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentSomething(response: Main.MainData.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    func presentSomething(response: Main.MainData.Response) {
        let viewModel = Main.MainData.ViewModel(mainData: response.mainData, isPaginating: false)
        
        //Sending main data to ViewController
        
        viewController?.displayMainData(viewModel: viewModel)
    }
}
