//
//  MainModels.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: MainData Models
    
    enum MainData
    {
        struct Request
        {
            let page : Int
        }
        
        struct Response
        {
            let mainData: [MainItemModel]
        }
        
        struct ViewModel
        {
            let mainData: [MainItemModel]
            let isPaginating: Bool
        }
        
    }
}
