//
//  MainRouter.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    var navigationController: UINavigationController? { get }
    func routeToDetails(data: MainItemModel)
}

class MainRouter: NSObject, MainRoutingLogic {
    
    
    weak var navigationController: UINavigationController?
    weak var viewController: MainViewController?
    
    //Route to DetailsViewController and pass data from mainViewController
    
    func routeToDetails(data: MainItemModel) {
        let detailVC = DetailsViewController()
        let router = DetailsRouter()
        router.viewController = detailVC
        detailVC.setup(data: data)
        
        navigationController = viewController?.navigationController
        navigationController?.pushViewController(detailVC, animated: true)
    }
}
