//
//  DetailsPresenter.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentCommentsData(response: Details.Comments.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?
    
    //Sending commets data to VC
    func presentCommentsData(response: Details.Comments.Response) {
        let viewModel = Details.Comments.ViewModel(finalData: response.items)
        viewController?.dispalayFinalDaata(viewModel: viewModel)
    } 
}
