//
//  DetailsInteractor.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func fetchCommentsData()
}
class DetailsInteractor: DetailsBusinessLogic {
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    var mainId: Int?
    
    // MARK: Fetch commetns data and send response to DetailsPresenter
    
    func fetchCommentsData() {
        guard let mainId = mainId else {return}
        
        worker = DetailsWorker()
        worker?.fetchComments(id: mainId, completion: {[weak self] items in
            guard let items = items else {return}
            let response = Details.Comments.Response(items: items)
            self?.presenter?.presentCommentsData(response: response)
        })
    }
    
}
