//
//  DetailsRouter.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}
class DetailsRouter: NSObject, DetailsRoutingLogic {
    weak var viewController: DetailsViewController?
}
