//
//  DetailsModels.swift
//  DataFetcherTest
//
//  Created by Davron on 10.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details
{
    // MARK: Detail Models
    
    enum Comments
    { 
        struct Response
        {
            let items: [DetailsItemModel]
        }
        
        struct ViewModel
        {
            let finalData: [DetailsItemModel]
        }
    }
    
}
